CREATE TABLE IF NOT EXISTS ev_customer_features (
    id BIGINT NOT NULL,
    source_set VARCHAR(8) NOT NULL,
    age SMALLINT UNSIGNED NOT NULL,
    annual_income_usd DOUBLE NOT NULL,
    daily_commute_km DOUBLE NOT NULL,
    number_of_cars_owned TINYINT UNSIGNED NOT NULL,
    charging_stations_near_home SMALLINT UNSIGNED NOT NULL,
    charging_stations_near_work SMALLINT UNSIGNED NOT NULL,
    environmental_concern_level DOUBLE NOT NULL,
    gender VARCHAR(16) NOT NULL,
    city_type VARCHAR(16) NOT NULL,
    current_car_type VARCHAR(24) NOT NULL,
    home_charging_possible VARCHAR(3) NOT NULL,
    subsidy_available VARCHAR(3) NOT NULL,
    range_anxiety_level VARCHAR(12) NOT NULL,
    will_buy_ev VARCHAR(3) NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_feature_source (source_set),
    INDEX idx_city_type (city_type),
    INDEX idx_subsidy (subsidy_available),
    INDEX idx_home_charging (home_charging_possible),
    CONSTRAINT chk_feature_source CHECK (source_set IN ('train', 'test')),
    CONSTRAINT chk_feature_target CHECK (will_buy_ev IS NULL OR will_buy_ev IN ('Yes', 'No'))
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ev_model_predictions (
    id BIGINT NOT NULL,
    source_set VARCHAR(8) NOT NULL,
    actual_target DOUBLE NULL,
    predicted_probability DOUBLE NOT NULL,
    prediction_decile TINYINT UNSIGNED NOT NULL,
    prediction_percentile DOUBLE NOT NULL,
    model_name VARCHAR(80) NOT NULL,
    model_version VARCHAR(80) NOT NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_prediction_source (source_set),
    INDEX idx_propensity (predicted_probability DESC),
    INDEX idx_prediction_decile (source_set, prediction_decile),
    CONSTRAINT fk_prediction_customer FOREIGN KEY (id) REFERENCES ev_customer_features (id) ON DELETE CASCADE,
    CONSTRAINT chk_prediction_probability CHECK (predicted_probability BETWEEN 0 AND 1),
    CONSTRAINT chk_prediction_decile CHECK (prediction_decile BETWEEN 1 AND 10)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ev_customer_segments (
    id BIGINT NOT NULL,
    source_set VARCHAR(8) NOT NULL,
    customer_segment VARCHAR(48) NOT NULL,
    segmentation_score DOUBLE NOT NULL,
    high_potential_flag BOOLEAN NOT NULL,
    segment_method VARCHAR(120) NOT NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_segment_source (source_set),
    INDEX idx_segment (customer_segment),
    INDEX idx_high_potential (high_potential_flag),
    CONSTRAINT fk_segment_customer FOREIGN KEY (id) REFERENCES ev_customer_features (id) ON DELETE CASCADE,
    CONSTRAINT chk_segmentation_score CHECK (segmentation_score BETWEEN 0 AND 1)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ev_model_metrics (
    metric_id BIGINT NOT NULL AUTO_INCREMENT,
    experiment_group VARCHAR(48) NOT NULL,
    model_name VARCHAR(80) NOT NULL,
    model_version VARCHAR(80) NOT NULL,
    validation_type VARCHAR(80) NOT NULL,
    seed INT NULL,
    fold INT NULL,
    roc_auc DOUBLE NULL,
    accuracy DOUBLE NULL,
    precision_score DOUBLE NULL,
    recall_score DOUBLE NULL,
    f1_score DOUBLE NULL,
    log_loss DOUBLE NULL,
    std_roc_auc DOUBLE NULL,
    fit_seconds DOUBLE NULL,
    predict_seconds DOUBLE NULL,
    parameters TEXT NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (metric_id),
    INDEX idx_metric_model (model_name, model_version),
    INDEX idx_metric_validation (validation_type),
    INDEX idx_metric_auc (roc_auc DESC),
    CONSTRAINT chk_metric_auc CHECK (roc_auc IS NULL OR roc_auc BETWEEN 0 AND 1)
) ENGINE=InnoDB;
